In [2]:
import numpy as np
import pandas as pd

A=np.array([[2,0,1,2,0],
            [2,-1,0,1,1],
            [0,1,2,1,2],
            [-2,0,2,-1,2],
            [2,0,0,1,1]])
print("Compute the following determinant efficiently:")
print(A)

print("the determinat is:")

Det_A=np.linalg.det(A)

print(Det_A)

Compute the following determinant efficiently:
[[ 2  0  1  2  0]
 [ 2 -1  0  1  1]
 [ 0  1  2  1  2]
 [-2  0  2 -1  2]
 [ 2  0  0  1  1]]
the determinat is:
6.000000000000003


In [16]:
import numpy as np
from scipy.linalg import eig

eigenvalues, eigenvectors = eig(A)

A = np.array([[1, 0], [1, 1]])

print("this is the Eigen value:")
print(eigenvalues)
print("\n")
print("this is the Eigen vector: ")
print(eigenvectors)

for i in range(len(eigenvalues)):
    print(f"Eigenspace for eigenvalue {eigenvalues[i]}:")
    eig_space = eigenvectors[:, i]
    print(eig_space)

this is the Eigen value:
[1.+0.j 1.+0.j]


this is the Eigen vector: 
[[ 0.00000000e+00  2.22044605e-16]
 [ 1.00000000e+00 -1.00000000e+00]]
Eigenspace for eigenvalue (1+0j):
[0. 1.]
Eigenspace for eigenvalue (1+0j):
[ 2.22044605e-16 -1.00000000e+00]
