In [1]:
import numpy as np
import pandas as pd 
import sympy as sp

#Matrix A = linear equation of the Maximum Blood presure
A= np.array([[1,1,0,0,0],
              [0,1,1,0,0],
              [0,0,1,1,0],
              [1,0,0,1,1]])

X1, X2, X3, X4, X5 = sp.symbols('X1 X2 X3 X4 X5')

#MA = Maximum Blood presure
MA= np.array([[28],
              [130],
              [123],
              [3+X1]])

#Matrix B = Minimum Blood presure
B= np.array([[1,-1,0,0,0],
            [0,-1,1,0,0],
            [0,0,1,-1,0],
            [1,0,0,1,-1]])

MB= np.array([[8],
              [110],
              [117],
              [3-X1]])

print("Matrix of the Maximum Blood presure")
print(A,"\n")
print(MA,"\n")

print("Matrix of the Minimum Blood presure")
print(B,"\n")
print(MB,"\n")


Matrix of the Maximum Blood presure
[[1 1 0 0 0]
 [0 1 1 0 0]
 [0 0 1 1 0]
 [1 0 0 1 1]] 

[[28]
 [130]
 [123]
 [X1 + 3]] 

Matrix of the Minimum Blood presure
[[ 1 -1  0  0  0]
 [ 0 -1  1  0  0]
 [ 0  0  1 -1  0]
 [ 1  0  0  1 -1]] 

[[8]
 [110]
 [117]
 [3 - X1]] 



In [2]:
print("Extraction equation from Matrix\n")
print("when the range in Max")

#Max N= equation N of maximum range
 
 #Define the equations
Max1 = sp.Eq(X1 + X2, 28)
Max2 = sp.Eq(X2 + X3, 130)
Max3 = sp.Eq(X3 + X4, 123)
Max4 = sp.Eq(X4 + X5, 3 + X1)

# Display equations
print(Max1)
print(Max2)
print(Max3)
print(Max4)

# MaxE soultion of maximum range equations
MaxE= sp.solve([Max1,Max2,Max3,Max4],
             (X1,X2,X3,X4,X5))

print("\nSolution in Maximum range in X1, X2, X3, X4, X5:")
print(MaxE,"\n")



Extraction equation from Matrix

when the range in Max
Eq(X1 + X2, 28)
Eq(X2 + X3, 130)
Eq(X3 + X4, 123)
Eq(X4 + X5, X1 + 3)

Solution in Maximum range in X1, X2, X3, X4, X5:
{X1: X5/2 + 9, X2: 19 - X5/2, X3: X5/2 + 111, X4: 12 - X5/2} 



In [3]:
print("Extraction equation from Matrix\n")
print("when the range in Min")

#min N= equation N of minimum range
 
 #Define the equations
min1 = sp.Eq(-X2+X1, 8)
min2 = sp.Eq(-X3+X2, 110)
min3 = sp.Eq(-X4+X3, 117)
min4 = sp.Eq(-X5+X4, 3 - X1)

# Display equations
print(min1)
print(min2)
print(min3)
print(min4)

# MaxE soultion of maximum range equations
minE= sp.solve([min1,min2,min3,min4],
             (X1,X2,X3,X4,X5))

print("\nSolution in minimum range in X1, X2, X3, X4, X5:")
print(minE,"\n")



Extraction equation from Matrix

when the range in Min
Eq(X1 - X2, 8)
Eq(X2 - X3, 110)
Eq(X3 - X4, 117)
Eq(X4 - X5, 3 - X1)

Solution in minimum range in X1, X2, X3, X4, X5:
{X1: X5/2 + 119, X2: X5/2 + 111, X3: X5/2 + 1, X4: X5/2 - 116} 

